app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    BreakActivities_id = db.Column(db.Integer,db.ForeignKey('BreakActivities.id'))
    password_hash = db.Column(db.String(255))
    def __repr__(self):
        return f'User {self.username}
class Activity(db.Model):
    __tablename__ = 'BreakActivities'

    id = db.Column(db.Integer,primary_key = True)
    Activity = db.Column(db.String(255))
     users = db.relationship('User',backref = 'role',lazy="dynamic")
    

    def __repr__(self):
        return f'User {self.Activity}' 
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@property
def password(self):
    raise AttributeError('You cannot read the password attribute')

@password.setter
    def password(self, password):
            self.pass_secure = generate_password_hash(password)
def verify_password(self,password):
    return check_password_hash(self.pass_secure,password)

    

app/main/authentication/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,PasswordField,BooleanField
from wtforms.validators import Required,Email,EqualTo,Length
from wtforms import ValidationError
from ..models import User

class RegistrationForm(FlaskForm):
    username=StringField('Username',validators=[Required()])
    email=StringField('Email',validators=[Required(),Email()])
    password=PasswordField('password',validators=Required())
    confirm password=PasswordField('confirm password',validators=[Required(),Equal To('password')])
    submit=SubmitField('Sign up')

    def validate_email(self,data_field):
        if User.query.filter_by(email =data_field.data).first():
            raise ValidationError('There is an account with that email')

    def validate_username(self,data_field):
        if User.query.filter_by(username = data_field.data).first():
            raise ValidationError('That username is taken')

class LoginFormForm(FlaskForm):
    email=StringField('Email',validators=[Required(),Email()])
    password=PasswordField('password',validators=Required())
    remember=BooleanField('Remember me')
    submit=SubmitField('Login')
class SettimerForm(FlaskForm):
    WorkingHours=StringField('Work duration',validators=[Required, Length(min=1,max=3)])
    breaktime=StringField('Break duration' validators=[Required, Length(min=5,max=9)])
    activity=TextAreaField('Break Activity' validators=[Required])
def validate_email(self,data_field):
    if User.query.filter_by(email =data_field.data).first():
        raise ValidationError('There is an account with that email')

def validate_username(self,data_field):
    if User.query.filter_by(username = data_field.data).first():
        raise ValidationError('That username is taken')
               
    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,PasswordField,BooleanField
from wtforms.validators import Required,Email,EqualTo,Length

class RegistrationForm(FlaskForm):
    username=StringField('Username',validators=[Required()])
    email=StringField('Email',validators=[Required(),Email()])
    password=PasswordField('password',validators=Required())
    confirm password=PasswordField('confirm password',validators=[Required(),Equal To('password')])
    submit=SubmitField('Sign up')

class LoginFormForm(FlaskForm):
    email=StringField('Email',validators=[Required(),Email()])
    password=PasswordField('password',validators=Required())
    remember=BooleanField('Remember me')
    submit=SubmitField('Login')
class SettimerForm(FlaskForm):
    WorkingHours=StringField('Work duration',validators=[Required, Length(min=1,max=3)])
    breaktime=StringField('Break duration' validators=[Required, Length(min=5,max=9)])
    activity=TextAreaField('Break Activity' validators=[Required])
def validate_email(self,data_field):
    if User.query.filter_by(email =data_field.data).first():
        raise ValidationError('There is an account with that email')

def validate_username(self,data_field):
    if User.query.filter_by(username = data_field.data).first():
        raise ValidationError('That username is taken')
               
    

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from forms import RegistrationForm ,LoginForm
from flask_bootstrap import Bootstrap
from config import config_options
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'authentication.login'

#initializing flask extentions
bootstrap=Bootstrap()


def create_app(config_name):
    app=Flask(__name__)
    
    from .authentication import authentication as authentication_blueprint
    app.register_blueprint(authentication_blueprint,url_prefix = '/authenticate')
    app.config['SECRET_KEY']='KAROL!#$@2!0%2&1?'
    app.config['sqlalchemy_batabase_URI']=''
    db=SQLAlchemy(app)

    #initializing flask extentions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    #registering blueprints
    from .main import main as main_bueprint
    app.register_blueprint(main_bueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main=Blueprint('authentication',__name__)
from . import views

app/main/authentication/__init__.py
from.import views,forms

app/main/authentication/views.py
from flask import render_template,request,redirect,url_for,flash
from app import app
from flask_login import login_user,logout_user,login_required
from .forms import RegistrationForm,LoginForm


@authentication.route('/register',methods=["GET","POST"])
def register():
    form=RegistrationForm()
    if form.validate_on_submit():
        flash(f'Account created for {form.username.data}','success')
        word = form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('authentication.login'))
        title = "New Account"
    return render_template('register.html',title=Register,form=form)
@authentication.route('/login')
def login():
    form=LoginForm()
    return render_template('login.html',title=Login,form=form)
@authentication.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for("index.index"))

app/main/views.py
from flask import render_template
from . import authentication
from flask_login import login_required

@main.route('/movie/review/new/<int:id>', methods = ['GET','POST'])
@login_required
def User(id):

app/views.py
from flask import render_template
from app import app

#views
@app.route('/')
def index():
    title=Welcome To Promodoro Timer
    return render_template(index.html,title=title)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% with messages=get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category,message in messages%}
<div class="alert  alert- {{category}} ">
    {{message}}
</div>
{% endfor %}
{% endif%}
{% endwith %}
{% block content%}
    
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
<!--content block -->
{% block content %}
{{title}}
{% endblock%

app/templates/login.html
{% extends 'bootstrap/base.html'%}
{% block content %}
    <div class="content">
        <form method="POST" action="">
            {{form.hidden_tag()}}
            <fieldset class=formgroup>
                <legend class=bt-1,mb-4>Login</legend>
                <div class="form-group">
                    {{ form.email.label (class="form-control-label") }}
                    {{ form.email(class="form-control,form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.password.label (class="form-control-label") }}
                    {{ form.password(class="form-control,form-control-lg") }}
                </div>
            </fieldset>
            <div class="form-group btn btn-outline-info">
                {{form.submit() "}}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't Have An Account? <a class="ml-2"href=" {{url_for('authentication.register')}} ">Sing up</a>
        </small>
    </div>
{% endblock content %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> log in </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
        </div>

    </div>
</div>

app/templates/register.html
{% extends 'bootstrap/base.html'%}
{% block content %}
    <div class="content">
        <form method="POST" action="">
            {{form.hidden_tag()}}
            <fieldset class=formgroup>
                <legend class=bt-1,mb-4>Join Today</legend>
                <div class="form-group">
                    {{ form.username.label (class="form-control-label") }}
                    {% if form.username.errors%}
                    {{form.username}}
                    <div class="invalid-feedback">
                        {%for error in from.username.errors%}
                        <span> {{error}}  </span>
                        {% endfor %}
                    </div>
                    {% elseif %}
                        {{ form.username(class="form-control,form-control-lg") }}
                    {% endif %}
                    
                </div>
                <div class="form-group">
                    {{ form.email.label (class="form-control-label") }}
                    {% if form.email.errors%}
                    {{form.email}}
                    <div class="invalid-feedback">
                        {%for error in from.email.errors%}
                        <span> {{error}}  </span>
                        {% endfor %}
                    </div>
                    {% elseif %}
                    {{ form.email(class="form-control,form-control-lg") }}
                    {% endif %}
                    
                </div>
                <div class="form-group">
                    {{ form.password.label (class="form-control-label") }}
                    {% if form.password.errors%}
                    {{form.password}}
                    <div class="invalid-feedback">
                        {%for error in from.password.errors%}
                        <span> {{error}}  </span>
                        {% endfor %}
                    </div>
                    {% elseif %}
                    {{ form.password(class="form-control,form-control-lg") }}
                    {% endif %}
                    
                </div>
                <div class="form-group ">
                    {{ form.confirm_password.label (class="form-control-label") }}
                    {% if form.confirm_password.errors%}
                    {{form.confirm_password}}
                    <div class="invalid-feedback">
                        {%for error in from.confirm_password.errors%}
                        <span> {{error}}  </span>
                        {% endfor %}
                    </div>
                    {% elseif %}
                    {{ form.confirm_password(class="form-control,form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group btn btn-outline-info">
                {{form.submit "}}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2"href=" {{url_for('login')}} ">Sing in</a>
        </small>
    </div>
    


{% endblock content %}

app/templates/settings.html
{% extends 'base.html' %}{% import 'bootstrap/wtf.html' as wtf%}

{% block styles%}
        {{ super() }}
        <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
        <link href="https://fonts.googleapis.com/css?family=Beth+Ellen|Lobster|Monoton&display=swap" rel="stylesheet">
        {% endblock %}
<!-- content -->
<div class="container">
    {% block content %}
    <div class="jumbotron text-center">
        <h1>
            {{app_name}}
        </h1>
    </div>
    <!--Flash message -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert"></button> {{ message }}
    </div>
    {% endfor %}
    <div class="col-md-4"></div>
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
    <div class="col-md-4"></div>
    {% endblock %}
</div>

app/templates/unwind.html
{% extends 'base.html' %}

<!-- content -->

{% block content %} {{app_name}}
<button class="btn btn-primary">hello world</button> 
{% endblock %}